#!/usr/bin/env python3
"""Plan version 2, the tutoring hotfix's data (repair plan WS5 T1 item 6,
Appendix B task 20, and task 17's line-name mapping).

What this proves:
  1. Version 1 (the default, and MTG_PLAN_VERSION unset) is byte-identical to
     the plans built before versions existed:
       - on synthetic decks, against a golden file generated by the pre-hotfix
         deck_plan.py (commit REF) with `--write-golden`;
       - on every bundled deck with the real card and combo caches, against the
         pre-hotfix module read from git (skipped, and said so, without git).
  2. Version 2, per the plan JSON contract shared with the shim:
       - Thassa's Oracle + Demonic Consultation stays in plan.lines;
       - Hullbreaker Horror + Sol Ring moves to threatLines only, and its
         pieces lose the blanket value 8;
       - Magda + Clock of Omens + Liquimetal Torque leaves plan.lines. This is
         documented and intended: Spellbook gives it no win feature, and it is
         the steer that overrode Portal to Phyrexia in 33 of 47 cases. WS8
         restores it as an expert-banded finisher with steer: false;
       - a Kess-like deck gets graveyardTargets for its reanimation targets
         and its castable-from-graveyard spells, and NOT for Sol Ring;
       - self-loss (Pact of Negation) and saboteur text are no longer
         finishers; opponent-loss and poison text still are;
       - the opponent-facing threat list is version 1's;
       - line and target names are the names Forge uses, from the Forge index
         when it is built and from the fallbacks when it is not;
       - the fix flags are all true and planVersion is 2.

Synthetic card facts and combo lines (feature strings copied from real
Spellbook records); a temp MTG_DATA_DIR, so the tracked plan_feedback.json is
never written; no network, no Forge.

Hash seed: version 1 orders tied threat cards by set iteration, which follows
Python's per-process string hash seed, so version 1 is only reproducible
byte for byte under one seed (true before this change too). The test re-runs
itself with PYTHONHASHSEED=0, the seed the golden file was written under.
The comparisons against the reference module run in one process and are
exact under any seed. Version 2 breaks those ties by name.

Run: py engine/tests/test_plan_hotfix.py
     py engine/tests/test_plan_hotfix.py --write-golden   # regenerate from REF
"""
from __future__ import annotations

import glob
import json
import os
import subprocess
import sys
import tempfile
import types
from pathlib import Path

ENGINE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ENGINE))
import cards  # noqa: E402
import combos  # noqa: E402
import deck_plan  # noqa: E402
import forge_index  # noqa: E402

# main before the hotfix. Version 1 is frozen at this commit's behaviour: a
# DELIBERATE change to version-1 plans must move REF, regenerate the golden
# file and say why in the commit.
REF = "ef80299"
GOLDEN = ENGINE / "tests" / "fixtures" / "plan_hotfix_v1_golden.json"

_REAL_GET_MANY = cards.get_many
_REAL_COMBOS = combos.combos_for_dck
_REAL_LOAD_INDEX = forge_index.load_index


def creature(text: str, cmc: int, power: str = "2", sub: str = "Wizard") -> dict:
    return {"oracle_text": text, "type_line": f"Creature — {sub}", "cmc": cmc,
            "power": power, "toughness": power}


FACTS = {
    # --- the cEDH-style deck ------------------------------------------------
    "Tymna Toy": {"oracle_text": "Lifelink", "type_line": "Legendary Creature — Cleric",
                  "cmc": 2, "power": "2", "toughness": "2"},
    "Thassa's Oracle": creature("When this creature enters, look at the top X cards of your "
                                "library. If X is greater than or equal to the number of cards "
                                "in your library, you win the game.", 2, "1", "Merfolk"),
    "Demonic Consultation": {"oracle_text": "Name a card. Exile the top six cards of your "
                                            "library, then reveal cards until you reveal the "
                                            "named card.", "type_line": "Instant", "cmc": 1},
    "Tainted Pact": {"oracle_text": "Exile the top card of your library. Repeat this until "
                                    "you choose to stop.", "type_line": "Instant", "cmc": 2},
    "Hullbreaker Horror": creature("Flash\nThis spell can't be countered.\nWhenever you cast a "
                                   "spell, return target nonland permanent to its owner's hand.",
                                   7, "7", "Kraken Horror"),
    "Sol Ring": {"oracle_text": "{T}: Add {C}{C}.", "type_line": "Artifact", "cmc": 1},
    "Mechanized Production": {"oracle_text": "At the beginning of your upkeep, create a copy of "
                                             "enchanted artifact. Then if you control eight "
                                             "artifacts with the same name, you win the game.",
                              "type_line": "Enchantment — Aura", "cmc": 4},
    # Forge names this adventure card by its creature face; Spellbook by both.
    "James, Wandering Dad": creature("Vigilance", 5, "4", "Human Scientist"),
    # Self-loss text: a counterspell, not a finisher (v1 scored it 8).
    "Pact of Negation": {"oracle_text": "Counter target spell.\nAt the beginning of your next "
                                        "upkeep, pay {3}{U}{U}. If you don't, you lose the "
                                        "game.", "type_line": "Instant", "cmc": 0},
    # Saboteur text: card advantage, not a finisher (v1 scored it 8).
    "Ragavan Toy": creature("Whenever this creature deals combat damage to a player, "
                            "exile the top card of that player's library.", 1, "2", "Monkey"),
    # Opponent-loss and poison text stay finishers in version 2.
    "Door Toy": {"oracle_text": "{T}: Target player loses the game.", "type_line": "Artifact",
                 "cmc": 5},
    "Poison Toy": creature("Toxic 1 (A player with ten or more poison counters loses the "
                           "game.)", 2, "1", "Phyrexian"),
    "Island": {"oracle_text": "({T}: Add {U}.)", "type_line": "Basic Land — Island", "cmc": 0},
    # --- the Magda deck -----------------------------------------------------
    "Magda, Brazen Outlaw": {"oracle_text": "Other Dwarves you control get +1/+0.",
                             "type_line": "Legendary Creature — Dwarf Berserker", "cmc": 2,
                             "power": "2", "toughness": "1"},
    "Clock of Omens": {"oracle_text": "Tap two untapped artifacts you control: Untap target "
                                      "artifact.", "type_line": "Artifact", "cmc": 4},
    "Liquimetal Torque": {"oracle_text": "{T}: Add {C}.\n{T}: Target nonland permanent becomes "
                                         "an artifact until end of turn.",
                          "type_line": "Artifact", "cmc": 2},
    "Portal to Phyrexia": {"oracle_text": "When this artifact enters, each opponent sacrifices "
                                          "three creatures.", "type_line": "Artifact",
                           "cmc": 9},
    "Narset's Reversal": {"oracle_text": "Copy target instant or sorcery spell, then return it "
                                         "to its owner's hand.", "type_line": "Instant",
                          "cmc": 2},
    "Expansion // Explosion": {"oracle_text": "Copy target instant or sorcery spell.",
                               "type_line": "Instant // Instant", "cmc": 2, "layout": "split"},
    "Mountain": {"oracle_text": "({T}: Add {R}.)", "type_line": "Basic Land — Mountain",
                 "cmc": 0},
    # --- the Kess-like deck -------------------------------------------------
    "Kess, Dissident Mage": {"oracle_text": "Flying\nDuring each of your turns, you may cast an "
                                            "instant or sorcery spell from your graveyard.",
                             "type_line": "Legendary Creature — Human Wizard", "cmc": 4,
                             "power": "3", "toughness": "4"},
    "Reanimate": {"oracle_text": "Put target creature card from a graveyard onto the "
                                 "battlefield under your control.",
                  "type_line": "Sorcery", "cmc": 1},
    "Animate Dead": {"oracle_text": "Enchant creature card in a graveyard\nWhen this Aura "
                                    "enters, return enchanted creature card to the "
                                    "battlefield under your control.",
                     "type_line": "Enchantment — Aura", "cmc": 2},
    "Unburial Rites": {"oracle_text": "Return target creature card from your graveyard to the "
                                      "battlefield.\nFlashback {3}{W}",
                       "type_line": "Sorcery", "cmc": 4},
    "Archon of Cruelty": creature("Flying\nWhenever this creature enters or attacks, target "
                                  "opponent sacrifices a creature.", 8, "6", "Archon"),
    "Stitcher's Supplier": creature("When this creature enters or dies, mill three cards.", 1,
                                    "1", "Zombie"),
    "Blasphemous Act": {"oracle_text": "This spell costs {1} less to cast for each creature on "
                                       "the battlefield. It deals 13 damage to each creature.",
                        "type_line": "Sorcery", "cmc": 9},
    "Faithless Looting": {"oracle_text": "Draw two cards, then discard two cards.\n"
                                         "Flashback {2}{R}", "type_line": "Sorcery", "cmc": 1},
    "Brainstorm": {"oracle_text": "Draw three cards, then put two cards from your hand on top "
                                  "of your library.", "type_line": "Instant", "cmc": 1},
    "Entomb": {"oracle_text": "Search your library for a card, put that card into your "
                              "graveyard, then shuffle.", "type_line": "Instant", "cmc": 1},
    "Unearth Toy": creature("Unearth {2}{B}", 3, "3", "Zombie"),
    # Grants flashback to ANOTHER card: not a graveyard card itself.
    "Snapcaster Toy": creature("Flash\nWhen this creature enters, target instant or sorcery "
                               "card in your graveyard gains flashback until end of turn.", 2),
    "Swamp": {"oracle_text": "({T}: Add {B}.)", "type_line": "Basic Land — Swamp", "cmc": 0},
    # --- a deck that does not reanimate --------------------------------------
    "Plain Commander": {"oracle_text": "Vigilance", "type_line": "Legendary Creature — Soldier",
                        "cmc": 3, "power": "3", "toughness": "3"},
    # --- a commander that grants flashback (Lier-style) ------------------------
    "Lier Toy": {"oracle_text": "Instant and sorcery cards in your graveyard have flashback.",
                 "type_line": "Legendary Creature — Human Wizard", "cmc": 5,
                 "power": "2", "toughness": "4"},
    # --- an unconverted DFC spelling in the deck itself. Cached before the
    # cache stored layouts (no "layout" key), so only the index can place it.
    "Birgi, God of Storytelling // Harnfel, Horn of Bounty": {
        "oracle_text": "Whenever you cast your hundredth spell this game, you win the game.",
        "type_line": "Legendary Creature — God // Legendary Artifact", "cmc": 3,
        "power": "3", "toughness": "3"},
    # --- a transform card the cache knows the layout of (forge_namer step 2) ---
    "Delver of Secrets // Insectile Aberration": {
        "oracle_text": "At the beginning of your upkeep, look at the top card of your library.",
        "type_line": "Creature — Human Wizard // Creature — Human Insect", "cmc": 1,
        "power": "1", "toughness": "1", "layout": "transform"},
}

DECKS = {
    "hotfix_cedh": ("Tymna Toy", ["Thassa's Oracle", "Demonic Consultation", "Tainted Pact",
                                  "Hullbreaker Horror", "Sol Ring", "Mechanized Production",
                                  "James, Wandering Dad", "Pact of Negation", "Ragavan Toy",
                                  "Door Toy", "Poison Toy", "Island", "Island"]),
    "hotfix_magda": ("Magda, Brazen Outlaw", ["Clock of Omens", "Liquimetal Torque",
                                              "Portal to Phyrexia", "Narset's Reversal",
                                              "Expansion // Explosion", "Sol Ring",
                                              "Mountain"]),
    "hotfix_kess": ("Kess, Dissident Mage", ["Reanimate", "Animate Dead", "Unburial Rites",
                                             "Archon of Cruelty", "Hullbreaker Horror",
                                             "Stitcher's Supplier", "Sol Ring",
                                             "Blasphemous Act", "Faithless Looting",
                                             "Brainstorm", "Entomb", "Unearth Toy",
                                             "Snapcaster Toy", "Island", "Swamp"]),
    "hotfix_plain": ("Plain Commander", ["Archon of Cruelty", "Faithless Looting",
                                         "Brainstorm", "Sol Ring", "Swamp"]),
    "hotfix_lier": ("Lier Toy", ["Brainstorm", "Blasphemous Act", "Archon of Cruelty",
                                 "Island"]),
    "hotfix_unconverted": ("Plain Commander", [
        "Birgi, God of Storytelling // Harnfel, Horn of Bounty", "Sol Ring", "Island"]),
}


def line(cards_: list[str], produces: list[str]) -> dict:
    return {"cards": cards_, "produces": produces}


# Real Spellbook variants (engine/combo_cache.json), per synthetic deck.
ORACLE_CONSULT = line(["Demonic Consultation", "Thassa's Oracle"],
                      ["Exile your library", "Win the game"])
TAINTED_PACT = line(["Tainted Pact", "Thassa's Oracle"], ["Win the game"])
HULLBREAKER = line(["Hullbreaker Horror", "Sol Ring"],
                   ["Infinite colorless mana", "Infinite storm count"])
JAMES = line(["James, Wandering Dad // Follow Him", "Mechanized Production"], ["Win the game"])
MAGDA = line(["Magda, Brazen Outlaw", "Clock of Omens", "Liquimetal Torque"],
             ["Infinite artifact ETB", "Infinite artifact tokens",
              "Infinite tapped Treasure tokens",
              "Put all artifact cards and a subset of creature cards from your library onto "
              "the battlefield"])
EXPLOSION = line(["Narset's Reversal", "Expansion // Explosion"], ["Infinite magecraft triggers"])

COMBOS = {
    "hotfix_cedh": [ORACLE_CONSULT, TAINTED_PACT, HULLBREAKER, JAMES],
    "hotfix_magda": [MAGDA, EXPLOSION],
    "hotfix_kess": [HULLBREAKER],
}


def fake_get_many(names, fetch=False):
    """Keyed like the real cache (by the name asked for); unknown names absent."""
    return {n: FACTS[n] for n in names if n in FACTS}


def fake_combos(path, fetch=False):
    included = COMBOS.get(Path(path).stem)
    if included is None:
        return {"identity": "", "included": [], "almost_included": []}
    return {"identity": "", "included": [dict(v, cards=list(v["cards"]),
                                              produces=list(v["produces"]))
                                         for v in included],
            "almost_included": []}


def fake_index() -> forge_index.ForgeIndex:
    """What Forge 2.0.13's index says about these names (layouts only)."""
    entries: dict[str, dict] = {}
    for n in FACTS:
        if " // " not in n:
            entries[n] = {"mode": None, "faces": [n], "types": FACTS[n]["type_line"]}
    entries["James, Wandering Dad"] = {"mode": "Adventure",
                                       "faces": ["James, Wandering Dad", "Follow Him"]}
    entries["Expansion // Explosion"] = {"mode": "Split", "faces": ["Expansion", "Explosion"]}
    entries["Delver of Secrets"] = {"mode": "DoubleFaced",
                                    "faces": ["Delver of Secrets", "Insectile Aberration"]}
    entries["Birgi, God of Storytelling"] = {"mode": "Modal",
                                             "faces": ["Birgi, God of Storytelling",
                                                       "Harnfel, Horn of Bounty"]}
    return forge_index.ForgeIndex(Path("."), {"forge_version": "test"}, entries, {})


def write_decks(d: Path) -> list[Path]:
    out = []
    for name, (cmdr, main) in DECKS.items():
        p = d / f"{name}.dck"
        body = ["[metadata]", f"Name={name}", "[Commander]", f"1 {cmdr}", "[Main]"]
        body += [f"1 {n}" for n in main]
        p.write_text("\n".join(body) + "\n", encoding="utf-8")
        out.append(p)
    return out


def synthetic(index=None) -> None:
    cards.get_many = fake_get_many
    combos.combos_for_dck = fake_combos
    forge_index.load_index = lambda version=None: index


def real() -> None:
    cards.get_many = _REAL_GET_MANY
    combos.combos_for_dck = _REAL_COMBOS
    forge_index.load_index = lambda version=None: None   # v1 never reads it


def reference_module() -> types.ModuleType | None:
    """deck_plan.py as it was at REF, or None when git or the commit is absent."""
    try:
        src = subprocess.run(["git", "-C", str(ENGINE), "show", f"{REF}:engine/deck_plan.py"],
                             capture_output=True, text=True, encoding="utf-8", timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    if src.returncode != 0 or "def build_plan" not in src.stdout:
        return None
    mod = types.ModuleType("deck_plan_ref")
    mod.__file__ = str(ENGINE / "deck_plan.py")
    exec(compile(src.stdout, f"{REF}:engine/deck_plan.py", "exec"), mod.__dict__)
    return mod


def dumps(plans: dict) -> str:
    return json.dumps(plans, indent=2)       # exactly as run_sim writes it


def write_golden(tmp: Path) -> None:
    ref = reference_module()
    if ref is None:
        sys.exit(f"--write-golden needs git and commit {REF}")
    synthetic()
    payload = dumps(ref.build_plans(write_decks(tmp)))
    with open(GOLDEN, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(payload + "\n")
    print(f"wrote {GOLDEN} from {REF}:engine/deck_plan.py")


def by_cards(lines: list[dict]) -> list[list[str]]:
    return [ln["cards"] for ln in lines]


def main() -> None:
    if os.environ.get("PYTHONHASHSEED") != "0":
        # See "Hash seed" in the module docstring.
        env = dict(os.environ, PYTHONHASHSEED="0")
        sys.exit(subprocess.call([sys.executable, str(Path(__file__).resolve()),
                                  *sys.argv[1:]], env=env))
    saved = {k: os.environ.get(k) for k in ("MTG_DATA_DIR", "MTG_PLAN_VERSION",
                                            "MTG_PLAN_FEEDBACK_APPLY")}
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        data = tmp / "data"
        data.mkdir()
        os.environ["MTG_DATA_DIR"] = str(data)       # plan_feedback.note_tags writes here
        os.environ.pop("MTG_PLAN_FEEDBACK_APPLY", None)
        os.environ.pop("MTG_PLAN_VERSION", None)
        try:
            if "--write-golden" in sys.argv:
                write_golden(tmp)
                return
            run(tmp)
        finally:
            real()
            forge_index.load_index = _REAL_LOAD_INDEX
            for k, v in saved.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v


def run(tmp: Path) -> None:
    tracked = ENGINE / "plan_feedback.json"
    before = tracked.stat().st_mtime_ns if tracked.exists() else None
    try:
        checks(tmp)
    finally:
        after = tracked.stat().st_mtime_ns if tracked.exists() else None
        assert before == after, "the tracked engine/plan_feedback.json was written"


def checks(tmp: Path) -> None:
    decks = write_decks(tmp)
    path = {p.stem: p for p in decks}

    # ------------------------------------------------ 1. version 1 unchanged --
    synthetic()
    v1_text = dumps(deck_plan.build_plans(decks))
    assert GOLDEN.is_file(), f"missing {GOLDEN}: run with --write-golden"
    assert v1_text + "\n" == GOLDEN.read_text(encoding="utf-8"), \
        "version-1 plans moved against the pre-hotfix golden file"
    assert dumps(deck_plan.build_plans(decks, plan_version=1)) == v1_text
    os.environ["MTG_PLAN_VERSION"] = "1"
    assert dumps(deck_plan.build_plans(decks)) == v1_text
    os.environ["MTG_PLAN_VERSION"] = ""
    assert dumps(deck_plan.build_plans(decks)) == v1_text
    os.environ.pop("MTG_PLAN_VERSION", None)
    _, lone = deck_plan.build_plan(path["hotfix_cedh"])
    assert lone == json.loads(v1_text)["decks"]["hotfix_cedh"], "build_plan defaults to v1"
    for plan in json.loads(v1_text)["decks"].values():
        assert not {"planVersion", "threatLines", "fix"} & set(plan), sorted(plan)
        assert set(plan["search"]) == {"targets", "context"}, plan["search"]
    print("  version 1 (default, flag unset, empty or 1) matches the pre-hotfix golden "
          "byte for byte: OK")

    ref = reference_module()
    bundled = sorted(glob.glob(str(ENGINE / "decks" / "*.dck")))
    if ref is None:
        print(f"  bundled-deck comparison SKIPPED: git or commit {REF} unavailable "
              f"(the synthetic golden above still holds)")
    else:
        real()
        diffs = [p for p in bundled
                 if dumps(ref.build_plans([p])) != dumps(deck_plan.build_plans([p]))
                 or dumps(ref.build_plans([p], synergy=True))
                 != dumps(deck_plan.build_plans([p], synergy=True))]
        assert not diffs, f"version 1 moved on bundled decks: {diffs}"
        print(f"  version 1 byte-identical to {REF} on all {len(bundled)} bundled decks "
              f"(real caches, synergy off and on): OK")
        synthetic()

    # The flag: 2 builds version 2 through build_plans; garbage is refused.
    os.environ["MTG_PLAN_VERSION"] = "2"
    assert deck_plan.env_plan_version() == 2
    via_env = deck_plan.build_plans([path["hotfix_cedh"]])
    assert via_env["decks"]["hotfix_cedh"]["planVersion"] == 2
    for bad in ("3", "two", "1.0"):
        os.environ["MTG_PLAN_VERSION"] = bad
        try:
            deck_plan.build_plans([path["hotfix_cedh"]])
        except ValueError:
            pass
        else:
            raise AssertionError(f"MTG_PLAN_VERSION={bad!r} must be refused")
    os.environ.pop("MTG_PLAN_VERSION", None)
    try:
        deck_plan.build_plan(path["hotfix_cedh"], plan_version=3)
    except ValueError:
        pass
    else:
        raise AssertionError("plan_version=3 must be refused")
    print("  MTG_PLAN_VERSION=2 builds version 2; 3, 'two' and '1.0' are refused: OK")

    # ------------------------------------------------------- 2. version 2 --
    v1 = json.loads(v1_text)["decks"]
    v2 = deck_plan.build_plans(decks, plan_version=2)["decks"]
    for name, plan in v2.items():
        assert next(iter(plan)) == "planVersion" and plan["planVersion"] == 2, name
        assert plan["fix"] == {"tutorReach": True, "commanderTutorZone": True,
                               "noForcedChoices": True, "graveyardDest": True}, plan["fix"]
        assert list(plan["search"]) == ["targets", "context", "graveyardTargets"], name
        assert len(plan["threatLines"]) == len(v1[name]["lines"]), name
        # Opponent-facing: the threat list is version 1's.
        assert set(plan["threat"]) >= set(v1[name]["threat"]), name
    print("  version 2 carries planVersion 2, threatLines, graveyardTargets and all four "
          "fix flags: OK")

    c1, c2 = v1["hotfix_cedh"], v2["hotfix_cedh"]
    pilot = by_cards(c2["lines"])
    assert ["Demonic Consultation", "Thassa's Oracle"] in pilot, pilot
    assert ["Tainted Pact", "Thassa's Oracle"] in pilot, pilot
    assert c2["weights"]["Thassa's Oracle"] == 8 and c2["roles"]["Thassa's Oracle"] == "combo-piece"
    assert c2["search"]["targets"]["Demonic Consultation"] == 8
    print("  Thassa's Oracle + Demonic Consultation stays in plan.lines (value 8): OK")

    threat = by_cards(c2["threatLines"])
    assert ["Hullbreaker Horror", "Sol Ring"] not in pilot, pilot
    assert ["Hullbreaker Horror", "Sol Ring"] in threat, threat
    assert c1["weights"]["Sol Ring"] == 8 and c1["search"]["targets"]["Sol Ring"] == 8
    assert c2["weights"].get("Sol Ring", 1) < 8 and c2["roles"]["Sol Ring"] != "combo-piece"
    assert c2["search"]["targets"]["Sol Ring"] == 5, c2["search"]["targets"]   # ramp tier
    assert c2["search"]["context"]["Sol Ring"] == {"hint": "ramp", "beforeRound": 5}
    assert c2["weights"]["Hullbreaker Horror"] == 4, c2["weights"]            # protection
    assert c2["search"]["targets"]["Hullbreaker Horror"] == 6                 # cmc bomb
    # ...but the table still fears them: both stay in the threat list.
    assert {"Sol Ring", "Hullbreaker Horror"} <= set(c2["threat"]), c2["threat"]
    assert set(c2["threat"]) == set(c1["threat"]) | {"James, Wandering Dad"}, \
        (sorted(c1["threat"]), sorted(c2["threat"]))
    print("  Hullbreaker Horror + Sol Ring moves to threatLines only; its pieces fall to "
          "their role tier; the threat list still names them: OK")

    m1, m2 = v1["hotfix_magda"], v2["hotfix_magda"]
    magda = ["Magda, Brazen Outlaw", "Clock of Omens", "Liquimetal Torque"]
    assert magda in by_cards(m1["lines"]) and magda not in by_cards(m2["lines"])
    assert magda in by_cards(m2["threatLines"])
    assert m2["lines"] == [], m2["lines"]          # no win line until WS8 composes one
    assert m1["search"]["targets"]["Clock of Omens"] == 8
    assert m2["search"]["targets"].get("Clock of Omens", 1) < 8, m2["search"]["targets"]
    assert m2["search"]["targets"]["Portal to Phyrexia"] >= 6
    print("  Magda + Clock of Omens + Liquimetal Torque leaves plan.lines (documented, "
          "intended; WS8 restores it as an expert finisher): OK")

    # _FINISHER: self-loss and saboteur text out; opponent-loss and poison in.
    t1, t2 = c1["search"]["targets"], c2["search"]["targets"]
    assert t1["Pact of Negation"] == 8 and t2.get("Pact of Negation", 1) < 8, (t1, t2)
    assert t1["Ragavan Toy"] == 8 and t2.get("Ragavan Toy", 1) < 8, (t1, t2)
    assert t1["Door Toy"] == t2["Door Toy"] == 8
    assert t1["Poison Toy"] == t2["Poison Toy"] == 8
    print("  Pact of Negation and saboteur text are no longer finishers; 'target player "
          "loses the game' and poison still are: OK")

    # ------------------------------------------------- graveyard targets --
    k2 = v2["hotfix_kess"]
    gy = k2["search"]["graveyardTargets"]
    assert "Sol Ring" not in gy, gy
    assert gy["Archon of Cruelty"] == 8, gy          # reanimation target, mana value 8
    assert gy["Hullbreaker Horror"] == 7, gy         # reanimation target, mana value 7
    assert "Stitcher's Supplier" not in gy, gy       # a 1-drop is not worth reanimating
    assert gy["Blasphemous Act"] == 6, gy            # Kess casts it; its search value 6
    for n in ("Brainstorm", "Entomb", "Reanimate"):
        assert gy[n] == 3, (n, gy)                    # Kess casts it; floor 3
    assert gy["Faithless Looting"] == 3 and gy["Unburial Rites"] == 3, gy   # flashback
    assert gy["Unearth Toy"] == 3, gy                 # unearth
    assert "Animate Dead" not in gy, gy               # an enchantment Kess cannot cast
    assert "Snapcaster Toy" not in gy, gy             # grants flashback, has none itself
    assert "Kess, Dissident Mage" not in gy and "Island" not in gy and "Swamp" not in gy
    assert all(1 <= val <= 9 for val in gy.values()), gy
    assert ["Hullbreaker Horror", "Sol Ring"] in by_cards(k2["threatLines"])
    assert k2["lines"] == []
    print("  Kess-like deck: reanimation targets and castable-from-graveyard spells get "
          "graveyardTargets; Sol Ring, lands, the commander and a 1-drop do not: OK")

    gy_plain = v2["hotfix_plain"]["search"]["graveyardTargets"]
    assert gy_plain == {"Faithless Looting": 3}, gy_plain
    print("  no reanimation and no Kess: only the flashback card is a graveyard target: OK")

    gy_lier = v2["hotfix_lier"]["search"]["graveyardTargets"]
    assert gy_lier == {"Brainstorm": 3, "Blasphemous Act": 6}, gy_lier
    print("  a commander that grants flashback lists the deck's instants and sorceries: OK")

    # ------------------------------------------------------ name mapping --
    # No index: the front face is a card in the deck, so the Spellbook spelling
    # maps to it; version 1 keeps Spellbook's spelling byte for byte.
    assert ["James, Wandering Dad // Follow Him", "Mechanized Production"] in by_cards(c1["lines"])
    assert c1["weights"].get("James, Wandering Dad", 1) < 8
    assert ["James, Wandering Dad", "Mechanized Production"] in pilot, pilot
    assert c2["weights"]["James, Wandering Dad"] == 8, c2["weights"]
    assert c2["search"]["targets"]["James, Wandering Dad"] == 8
    assert ["Narset's Reversal", "Expansion // Explosion"] in by_cards(m2["threatLines"])
    print("  no index: 'Front // Back' line names map to the deck's front face; a split "
          "card keeps 'A // B'; version 1 keeps Spellbook's spelling: OK")

    synthetic(index=fake_index())
    v2i = deck_plan.build_plans(decks, plan_version=2)["decks"]
    assert v2i["hotfix_cedh"]["lines"] == c2["lines"], v2i["hotfix_cedh"]["lines"]
    assert v2i["hotfix_magda"]["threatLines"] == m2["threatLines"]
    u2 = v2["hotfix_unconverted"]["search"]["targets"]
    u2i = v2i["hotfix_unconverted"]["search"]["targets"]
    birgi = "Birgi, God of Storytelling // Harnfel, Horn of Bounty"
    assert birgi in u2, u2                  # no index, no cached layout: left as pasted...
    assert u2i == {"Birgi, God of Storytelling": 8, "Sol Ring": 5}, u2i   # ...the index maps it
    assert v1["hotfix_unconverted"]["search"]["targets"] == u2       # v1 key as pasted
    # Every deck-keyed field is mapped too: no trace of the pasted spelling.
    un = v2i["hotfix_unconverted"]
    assert "Harnfel" not in json.dumps(un), json.dumps(un)[:400]
    assert un["roles"]["Birgi, God of Storytelling"], un["roles"]
    assert "Harnfel" in json.dumps(v1["hotfix_unconverted"])       # v1 untouched
    assert dumps(deck_plan.build_plans(decks)) == v1_text, "the index must not touch v1"
    print("  with the Forge index: the same line names, and a pasted DFC target key "
          "becomes Forge's front-face name; version 1 still untouched: OK")

    synthetic()
    namer = deck_plan.forge_namer(["Sol Ring"])
    # Step 2: the card cache's Scryfall layout, for a card not in this deck.
    assert namer("Delver of Secrets // Insectile Aberration") == "Delver of Secrets"
    assert namer("Expansion // Explosion") == "Expansion // Explosion"    # split layout
    assert namer("Unknown Front // Unknown Back") == "Unknown Front // Unknown Back"
    assert namer("Sol Ring") == "Sol Ring"
    print("  forge_namer fallbacks: cache layout maps a transform card, keeps a split card, "
          "leaves an unknown name alone: OK")

    # Synergy lines (opt-in) are archetype engines: threat lines, never pilot lines.
    syn = deck_plan.build_plans([path["hotfix_plain"]], synergy=True, plan_version=2)
    sp = syn["decks"]["hotfix_plain"]
    assert sp["lines"] == [] and all(ln.get("source") == "synergy" for ln in sp["threatLines"])
    print("  version 2 synergy lines go to threatLines only: OK")

    print("plan hotfix: ALL ASSERTIONS PASSED")


if __name__ == "__main__":
    main()
